config/routes.rb
App::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }
  
  resources :access_rights, :except => [:index, :show, :edit]
  
  resources :externals do
    member do
      get :destroy_photo
    end
  end
  
  resources :external_content_kinds, :helpsters, :product_firms, :recipe_sources, :stores, :units, :user_kinds, 
            :vendors, :wine_groups, :wine_kinds, :wine_colors
  
  resources :abouts,    :except => [:show]
  resources :conditions,:except => [:show]
  resources :contacts,  :except => [:show]
  
  resources :cooks, :cooking_schools, :ekos, :events, :healthies, :know_its, :ingredient_groups, 
            :recipe_authors, :recipe_source_kinds, :ingredients, :nostalgics, :products, 
            :recipe_kinds, :table_covers, :tools, :users, :wines  do
    resources :photos, :only => [:new, :create]
  end
  
  resources :external_content_kinds do
    resources :external_contents
  end
  
  resources :external_contents
  
  resources :comments, :except => [:edit]
  resources :original_recipes, :except => [:edit]
  
  resources :photos, :only => [:destroy]
  
  resources :recipes do
    resources :recipe_ingredients, :except => [:index]
    resources :recipe_wines, :except => [:index]
    resources :origins, :except => [:index]
    resources :photos, :only => [:new, :create]
    collection do
      get :manage
      get :refrigerator_search
    end
  end
  
  resources :recipe_menus, :only => [:index] do 
    member do 
      get :add_day_and_recipe_to_menu
      get :remove_recipe_from_day
    end
  end
  
  
  resources :vendings, :only => [:index, :create] do 
    member do 
      get :finish_up
    end
  end
  
  match "home/index", :to => "home#index"
  root :to => "home#index"
end

app/models/recipe_source_kind.rb
class RecipeSourceKind < ActiveRecord::Base
  has_many :recipe_sources,  :dependent => :destroy
  has_many :recipe_authors, :through => :recipe_sources
  has_many  :photos, :as => :holder, :dependent => :destroy
  validates_presence_of :title, :description
  
  def recipes
    Recipe.where(:id => Origin.where(:recipe_source_id => recipe_source_ids).map(&:recipe_id) )
  end
  
  def to_s
    title
  end
end

app/controllers/recipe_source_kinds_controller.rb
class RecipeSourceKindsController < InheritedResources::Base
  load_and_authorize_resource
end

app/views/recipe_source_kinds/_form.html.haml
= simple_form_for resource do |f|
  = f.input :title
  = f.input :description
  = f.input :url
  = f.input :url_title
  = f.submit

app/views/recipe_source_kinds/_recipe_source_kind.html.haml
%li= link_to recipe_source_kind, recipe_source_kind

app/views/recipe_source_kinds/edit.html.haml
%section
  = title "Urejanje vrste vira recepta"
  = render "form"
  = link_to_back
%aside

app/views/recipe_source_kinds/index.html.haml
%section
  = title "Vrste virov receptov"
  = helpster("recipe_source_kinds")
  
  - if can? :create, RecipeSourceKind
    %nav#editors-resource-menu
      %ul
        %li= link_to "Dodaj vrsto vira", new_resource_path
  
  = collection_list_renderer(collection)
%aside

app/views/recipe_source_kinds/new.html.haml
%section
  = title "Dodajanje vrste virov"
  = render "form"
  = link_to_back
%aside

app/views/recipe_source_kinds/show.haml
%section
  = title resource
  = render "common/update_destroy_resource_photo_menu", :resource => resource, :new_photo_path => new_recipe_source_kind_photo_path(resource)
  = render "common/single_photo", :resource => resource
  
  = render "common/redcloth_it", :content => resource.description
  
  - if resource.url.present? and resource.url_title.present?
    %p= link_to resource.url_title, resource.url
  
  = link_to_back
%aside