config/routes.rb
App::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }
  
  resources :access_rights, :except => [:index, :show, :edit]
  
  resources :externals do
    member do
      get :destroy_photo
    end
  end
  
  resources :external_content_kinds, :helpsters, :product_firms, :recipe_sources, :stores, :units, :user_kinds, 
            :vendors, :wine_groups, :wine_kinds, :wine_colors
  
  resources :abouts,    :except => [:show]
  resources :conditions,:except => [:show]
  resources :contacts,  :except => [:show]
  
  resources :cooks, :cooking_schools, :ekos, :events, :healthies, :know_its, :ingredient_groups, 
            :recipe_authors, :recipe_source_kinds, :ingredients, :nostalgics, :products, 
            :recipe_kinds, :table_covers, :tools, :users, :wines  do
    resources :photos, :only => [:new, :create]
  end
  
  resources :external_content_kinds do
    resources :external_contents
  end
  
  resources :external_contents
  
  resources :comments, :except => [:edit]
  resources :original_recipes, :except => [:edit]
  
  resources :photos, :only => [:destroy]
  
  resources :recipes do
    resources :recipe_ingredients, :except => [:index]
    resources :recipe_wines, :except => [:index]
    resources :origins, :except => [:index]
    resources :photos, :only => [:new, :create]
    collection do
      get :manage
      get :refrigerator_search
    end
  end
  
  resources :recipe_menus, :only => [:index] do 
    member do 
      get :add_day_and_recipe_to_menu
      get :remove_recipe_from_day
    end
  end
  
  
  resources :vendings, :only => [:index, :create] do 
    member do 
      get :finish_up
    end
  end
  
  match "home/index", :to => "home#index"
  root :to => "home#index"
end

app/models/helpster.rb
class Helpster < ActiveRecord::Base
  validates_presence_of :help, :container, :user_kind
  
  validate :container_already_set, :on => :create
  
  def container
    Container.find(container_id)
  end
  
  def user_kind
    UserKind.find_among_all(user_kind_id)
  end
  
  def container=(co)
    self.container_id = Container.find(co).id if Container.find(co)
  end
  
  def user_kind=(uk)
    self.user_kind_id = UserKind.find_among_all(uk).id if UserKind.find_among_all(uk)
  end
  
  def to_s
    container.title
  end
  
  private
  
  def container_already_set
    errors.add :user_kind, "Vrsti uporabnika ste že podali pomočnika za izbran vsebnik" if Helpster.find_by_user_kind_id_and_container_id(user_kind_id, container_id).present?
  end
end

app/controllers/helpsters_controller.rb
class HelpstersController < InheritedResources::Base
  load_and_authorize_resource
  
  def create
    create! { helpsters_path }
  end
  
  def update
    update! { helpsters_path }
  end
end

app/helpers/helpster_helper.rb
module HelpsterHelper
end

app/views/helpsters/_form.html.haml
= simple_form_for resource do |f|
  = f.input :container, :as => :select, :collection => Container.all, :prompt => "Izberite vsebnik", :value_method => Proc.new {|container| container.id }
  = f.input :user_kind, :as => :select, :collection => UserKind.all_with_admin, :prompt => "Izberite vrsto uporabnika", :value_method => Proc.new {|user_kind| user_kind.id }
  = f.input :help
  
  = f.submit

app/views/helpsters/edit.html.haml
%section
  = title "Urejanje pomočnika"
  = render "form"
  = link_to_back

app/views/helpsters/index.html.haml
%section
  = title "Pregled pomočnikov"

  - if can? :create, Helpster
    %nav#editors-resource-menu
      %ul
        %li= link_to "Dodaj pomoč uporabniku", new_resource_path

  %ul
    - collection.group_by{|helpsterino| Container.find(helpsterino.container_id).title }.each do |container, helpsters|
      %li        
        Pomoč za podstran
        %strong= " #{container}:"
        - if helpsters.any? 
          %ul
            - for helpster in helpsters
              %li
                Namenenjeno vrsti uporabnika 
                %em= UserKind.find_among_all(helpster.user_kind_id)
                (
                = link_to "Uredi", edit_helpster_path(helpster)
                , 
                = link_to "Izbriši", helpster, :method => :delete, :confirm => destroy_confirmation(helpster)
                )
                %p
                  %strong Vsebina:
                  = helpster.help

app/views/helpsters/new.html.haml
= title "Dodajanje pomoči"
= render "form"